name: Check for updates
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch: {}
jobs:
  flatpak-external-data-checker:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub/flatpak-external-data-checker
    if: github.repository_owner == 'flathub'
    strategy:
      matrix:
        branch: [ branch/5.15-21.08, branch/6.2 ]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: Flatpak External Data Checker
          GIT_COMMITTER_NAME: Flatpak External Data Checker
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
          EMAIL: ${{ github.actor }}@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --update --never-fork io.qt.qtwebengine.BaseApp.json
